services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: postgres-db
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5433:80"
    volumes:
      - db_pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
volumes:
  db_postgres_data:
    external: true
  db_pgadmin_data:
    external: true